<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="Tesis1.Index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="/Content/web.css" />
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <script src="Scripts/jquery-3.3.1.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>
</head>
<body>
    <form id="form1" runat="server" onsubmit="return false">
        <div class="Title"><h1>Bienvenidos al portal</h1></div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <video class="videoElement" id="video" playsinline autoplay></video>
                </div>
                <div class="col-md-6">
                    <fieldset>
                        <legend><h2>Configuraciones</h2></legend>
                        <div>
                            <div class="titulo">
                                <h3>Objetos</h3>
                            </div>
                            <div class="check">
                                <asp:CheckBox ID="CbxCasco" runat="server" Text="Casco" />
                                <br />
                                <asp:CheckBox ID="CbxChaleco" runat="server" Text="Chaleco" />
                            </div>
                        </div>
                        <div>
                            <div class="titulo">
                                <h3>Correo:</h3>
                            </div>
                            <div >
                                <asp:TextBox ID="TxtCorreo" runat="server"></asp:TextBox>
                            </div>
                        </div>
                        <div style="padding-top:5px;">
                            <asp:Button ID="BtnGuardar" runat="server" Text="Guardar" class="btn-primary" OnClick="BtnGuardar_Click"/>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div >
                <button class="btn-primary" id="snap" onclick="CapturarFrame()" style="">Capture</button>
            </div>

            <!-- Webcam video snapshot -->
            <canvas id="canvas" width="640" height="480" style="display: none"></canvas>
        </div>
    </form>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.3.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript" src="/Scripts/webcam.js"></script>
    <script>
        //Timer para capturar frames cada 6 segundos
        CapturarFrame();
        //window.setInterval(function () {
        //    CapturarFrame();
        //}, 300000);
    </script>
</body>
</html>
